/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectospand.Interfaces.Inventario;

/**
 *
 * @author ING. Lomelí
 */
public class RegistrarProductoForm extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProductoForm
     */
    public RegistrarProductoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblPrecioProducto = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        lblDescProducto = new javax.swing.JLabel();
        txtDescProducto = new javax.swing.JTextField();
        lblCantidadProducto = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        lblProveedor = new javax.swing.JLabel();
        jcombProveedor = new javax.swing.JComboBox<>();
        lblGananciaProducto = new javax.swing.JLabel();
        jcomGananciaProducto = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(230, 230, 250));
        setPreferredSize(new java.awt.Dimension(340, 529));

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        lblNombreProducto.setText("Nombre del producto*");

        txtNombreProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProducto.setText("Ingresa el nombre del producto");
        txtNombreProducto.setEnabled(false);

        lblPrecioProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioProducto.setForeground(new java.awt.Color(102, 102, 102));
        lblPrecioProducto.setText("Precio del producto*");

        txtPrecioProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioProducto.setText("Ingresa el precio del producto");
        txtPrecioProducto.setEnabled(false);

        lblDescProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescProducto.setForeground(new java.awt.Color(102, 102, 102));
        lblDescProducto.setText("Descripción del producto*");

        txtDescProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtDescProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescProducto.setText("Ingresa la descripción del producto");
        txtDescProducto.setEnabled(false);

        lblCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCantidadProducto.setForeground(new java.awt.Color(102, 102, 102));
        lblCantidadProducto.setText("Cantidad de producto*");

        txtCantidadProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadProducto.setText("Ingresa la cantidad de producto");
        txtCantidadProducto.setEnabled(false);

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(102, 102, 102));
        lblProveedor.setText("Proveedor del producto*");

        jcombProveedor.setEnabled(false);
        jcombProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombProveedorActionPerformed(evt);
            }
        });

        lblGananciaProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGananciaProducto.setForeground(new java.awt.Color(102, 102, 102));
        lblGananciaProducto.setText("Ganancia del producto (%)*");

        jcomGananciaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "20" }));
        jcomGananciaProducto.setEnabled(false);
        jcomGananciaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomGananciaProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioProducto)
                    .addComponent(txtPrecioProducto)
                    .addComponent(lblDescProducto)
                    .addComponent(txtDescProducto)
                    .addComponent(lblCantidadProducto)
                    .addComponent(txtCantidadProducto)
                    .addComponent(lblProveedor)
                    .addComponent(jcombProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGananciaProducto)
                    .addComponent(jcomGananciaProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreProducto))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNombreProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecioProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCantidadProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcombProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGananciaProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcomGananciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jcombProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombProveedorActionPerformed

    private void jcomGananciaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomGananciaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomGananciaProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcomGananciaProducto;
    private javax.swing.JComboBox<String> jcombProveedor;
    private javax.swing.JLabel lblCantidadProducto;
    private javax.swing.JLabel lblDescProducto;
    private javax.swing.JLabel lblGananciaProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtDescProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
