
package com.proyectospand.Interfaces.Login;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.proyectospand.Interfaces.confUI;
import com.proyectospand.ConexionDB.*;
import com.proyectospand.Entidades.Empleados;

import com.proyectospand.Interfaces.ventanaPrincipal.*;

public class Login extends javax.swing.JFrame {

    validarCredenciales autenticarCredenciales = new validarCredenciales();
    public Login() {
        initComponents();
        confUI.setImageComponent(lblLogoSPA, "iconoApp.png");
        confUI.setImageComponent(lblLogoLoginForm, "iconoApp.png");
        confUI.applyCustomFont(24f,lblNombreEmpresa,lblIniciarSesion);
        confUI.applyCustomFont(18f, lblUsuario,lblContrasena);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlFondoEmpresa = new javax.swing.JPanel();
        lblLogoSPA = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogoLoginForm = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblEmpresaLogin = new javax.swing.JLabel();
        bttnIniciarSesion = new javax.swing.JButton();
        pswContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoEmpresa.setBackground(new java.awt.Color(230, 230, 250));
        pnlFondoEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoSPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlFondoEmpresa.add(lblLogoSPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 210, 203));

        lblNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreEmpresa.setText("SPA NATURAL DAY");
        pnlFondoEmpresa.add(lblNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        pnlFondo.add(pnlFondoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 0, 320, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIniciarSesion.setText("INICIAR SESIÓN");

        txtUsuario.setForeground(java.awt.Color.lightGray);
        txtUsuario.setText("Ingresar el nombre del usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("USUARIO");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContrasena.setText("CONTRASENA");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblEmpresaLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmpresaLogin.setText("SPA NATURAL DAY");

        bttnIniciarSesion.setBackground(new java.awt.Color(194, 213, 230));
        bttnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttnIniciarSesion.setText("INICIAR SESIÓN");
        bttnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnIniciarSesionActionPerformed(evt);
            }
        });

        pswContrasena.setForeground(java.awt.Color.lightGray);
        pswContrasena.setText("**********");
        pswContrasena.setBorder(null);
        pswContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswContrasenaFocusGained(evt);
            }
        });
        pswContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswContrasenaMousePressed(evt);
            }
        });
        pswContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswContrasenaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblContrasena)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .addComponent(pswContrasena))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblLogoLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblEmpresaLogin))
                                .addComponent(lblIniciarSesion)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .addComponent(lblUsuario)
                                .addComponent(jSeparator1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(bttnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblLogoLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEmpresaLogin)
                        .addGap(44, 44, 44)))
                .addComponent(lblIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addGap(4, 4, 4)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnlFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {
        // Llama al método de autenticación con el nombre de usuario y contraseña
        Empleados empleado = autenticarCredenciales.autenticarLogin(txtUsuario.getText(), String.valueOf(pswContrasena.getPassword()));

        if (empleado != null) {
            try (Connection conexion = conexionDB.getIntance().getConnection()) {
                // Verifica si la conexión fue exitosa
                if (conexion != null) {
                    // Inicio de sesión exitoso, redirigir según el rol del empleado
                    redirigirSegunRol(empleado);
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error al obtener una conexión.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            } 
        } else {
            // Manejar el caso en que las credenciales son incorrectas
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas. Intenta de nuevo.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void redirigirSegunRol(Empleados empleado) {
        // Obtén el rol del empleado desde el objeto TipoEmpleado
        String rol = empleado.getTipo().getNombreTipo();
        
        // Redirige al usuario según su rol
        switch (rol) {
            case "Administrador":
                // Cargar la ventana principal del administrador
                menuPrincipalAdministrador adminVentana = new menuPrincipalAdministrador(empleado);
                adminVentana.setVisible(true);
                break;
            case "Recepcionista":
                menuPrincipalRecepcionista recepVentana = new menuPrincipalRecepcionista(empleado);
                recepVentana.setVisible(true);
                break;
            case "Inventarista":
                menuPrincipalInventarista inventVentana = new menuPrincipalInventarista(empleado);
                inventVentana.setVisible(true);
                break;
            default:
                // Mostrar mensaje si el rol no es reconocido
                JOptionPane.showMessageDialog(null, "Rol no reconocido: " + rol, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    
        // Cierra la ventana de login actual
        this.dispose();
    }

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(txtUsuario.getText().equals("Ingresar el nombre del usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if(String.valueOf(pswContrasena.getPassword()).isEmpty()){
            pswContrasena.setText("**********");
            pswContrasena.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void pswContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContrasenaMousePressed
        if(String.valueOf(pswContrasena.getPassword()).equals("**********")){
            pswContrasena.setText("");
            pswContrasena.setForeground(Color.black);
        }
        if(txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingresar el nombre del usuario");
            txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pswContrasenaMousePressed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if(txtUsuario.getText().equals("Ingresar el nombre del usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if(String.valueOf(pswContrasena.getPassword()).isEmpty()){
            pswContrasena.setText("**********");
            pswContrasena.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void pswContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswContrasenaFocusGained
        if(String.valueOf(pswContrasena.getPassword()).equals("**********")){
            pswContrasena.setText("");
            pswContrasena.setForeground(Color.black);
        }
        if(txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingresar el nombre del usuario");
            txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pswContrasenaFocusGained

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bttnIniciarSesionActionPerformed(null);
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void pswContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswContrasenaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bttnIniciarSesionActionPerformed(null); // Llama al método de inicio de sesión
        }
    }//GEN-LAST:event_pswContrasenaKeyPressed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblEmpresaLogin;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLogoLoginForm;
    private javax.swing.JLabel lblLogoSPA;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondoEmpresa;
    private javax.swing.JPasswordField pswContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
