package com.proyectospand.Interfaces.Proveedores;

import java.awt.Color;

/**
 *
 * @author omarr
 */
public class RegistrarProveedorForm extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProveedorForm
     */
    public RegistrarProveedorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreProv = new javax.swing.JLabel();
        txtNombreProv = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(230, 230, 250));

        lblNombreProv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreProv.setForeground(new java.awt.Color(102, 102, 102));
        lblNombreProv.setText("Nombre del Proveedor*");

        txtNombreProv.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProv.setText("Ingresa el nombre del proveedor");
        txtNombreProv.setEnabled(false);
        txtNombreProv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreProvFocusGained(evt);
            }
        });
        txtNombreProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreProvMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreProvMousePressed(evt);
            }
        });

        lblCalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(102, 102, 102));
        lblCalle.setText("Calle*");

        txtCalle.setForeground(new java.awt.Color(153, 153, 153));
        txtCalle.setText("Ingresa la calle");
        txtCalle.setEnabled(false);
        txtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCalleFocusGained(evt);
            }
        });
        txtCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCalleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCalleMousePressed(evt);
            }
        });

        lblColonia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblColonia.setForeground(new java.awt.Color(102, 102, 102));
        lblColonia.setText("Colonia*");

        txtColonia.setForeground(new java.awt.Color(153, 153, 153));
        txtColonia.setText("Ingresa la colonia");
        txtColonia.setEnabled(false);
        txtColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColoniaFocusGained(evt);
            }
        });
        txtColonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtColoniaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtColoniaMousePressed(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefono.setText("Télefono*");

        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Ingresa el teléfono");
        txtTelefono.setEnabled(false);
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
        });
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(102, 102, 102));
        lblCorreo.setText("Correo*");

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("Ingresa el correo");
        txtCorreo.setEnabled(false);
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
        });
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCorreoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtColonia, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNombreProv)
                                        .addComponent(txtNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addComponent(lblCalle)
                                        .addComponent(txtCalle, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                                    .addComponent(lblColonia)))
                            .addComponent(lblTelefono)))
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblNombreProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblColonia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreProvFocusGained
       if (txtNombreProv.getText().equals("Ingresa el nombre del proveedor")){
           txtNombreProv.setText("");
           txtNombreProv.setForeground(Color.black);
       }
    }//GEN-LAST:event_txtNombreProvFocusGained

    private void txtNombreProvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProvMousePressed
        if (txtNombreProv.getText().equals("Ingresa el nombre del proveedor")){
           txtNombreProv.setText("");
           txtNombreProv.setForeground(Color.black);
       }
    }//GEN-LAST:event_txtNombreProvMousePressed

    private void txtNombreProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProvMouseExited
        if (txtNombreProv.getText().isEmpty()){
           txtNombreProv.setText("Ingresa el nombre del proveedor");
           txtNombreProv.setForeground(Color.GRAY);
       }
    }//GEN-LAST:event_txtNombreProvMouseExited

    private void txtCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusGained
        if (txtCalle.getText().equals("Ingresa la calle")){
            txtCalle.setText("");
            txtCalle.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCalleFocusGained

    private void txtCalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleMousePressed
        if (txtCalle.getText().equals("Ingresa la calle")){
            txtCalle.setText("");
            txtCalle.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCalleMousePressed

    private void txtCalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleMouseExited
        if (txtCalle.getText().isEmpty()){
            txtCalle.setText("Ingresa la calle");
            txtCalle.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtCalleMouseExited

    private void txtColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColoniaFocusGained
        if (txtColonia.getText().equals("Ingresa la colonia")){
            txtColonia.setText("");
            txtColonia.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtColoniaFocusGained

    private void txtColoniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColoniaMousePressed
        if (txtColonia.getText().equals("Ingresa la colonia")){
            txtColonia.setText("");
            txtColonia.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtColoniaMousePressed

    private void txtColoniaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColoniaMouseExited
        if (txtColonia.getText().isEmpty()){
            txtColonia.setText("Ingresa la colonia");
            txtColonia.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtColoniaMouseExited

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
        if (txtTelefono.getText().equals("Ingresa el teléfono")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if (txtTelefono.getText().equals("Ingresa el teléfono")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtTelefonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseExited
        if (txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingresa el teléfono");
            txtTelefono.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtTelefonoMouseExited

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if (txtCorreo.getText().equals("Ingresa el correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if (txtCorreo.getText().equals("Ingresa el correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseExited
        if (txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingresa el correo");
            txtCorreo.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtCorreoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombreProv;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreProv;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
