
package com.proyectospand.Interfaces.Proveedores;
import java.awt.*;
/**
 *
 * @author omarr
 */
public class VentanaProveedor extends javax.swing.JPanel {

    /**
     * Creates new form VentanaProveedor
     */
    public VentanaProveedor() {
        initComponents();
        
        RegistrarProveedorForm rprov = new RegistrarProveedorForm();
        rprov.setSize(331,515);
        rprov.setLocation(0,0);
        pnlFormProv.removeAll();
        pnlFormProv.add(rprov, BorderLayout.CENTER);
        pnlFormProv.revalidate();
        pnlFormProv.repaint();
        //RegistrarProductoForm rp = new RegistrarProductoForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpcionesProveedor = new javax.swing.JPanel();
        lblRegistrarProveedor = new javax.swing.JLabel();
        lblInformacionProveedor = new javax.swing.JLabel();
        pnlFormProv = new javax.swing.JPanel();
        pnlVentanaProv = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        lblAgregar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEliminar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblGuardar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblCancelar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1180, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOpcionesProveedor.setBackground(new java.awt.Color(230, 230, 250));
        pnlOpcionesProveedor.setPreferredSize(new java.awt.Dimension(346, 567));

        lblRegistrarProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistrarProveedor.setText("¡REGISTRA UN PROVEEDOR!");

        lblInformacionProveedor.setForeground(new java.awt.Color(105, 105, 105));
        lblInformacionProveedor.setText("Completa la información del proveedor");

        pnlFormProv.setBackground(new java.awt.Color(230, 230, 250));

        javax.swing.GroupLayout pnlFormProvLayout = new javax.swing.GroupLayout(pnlFormProv);
        pnlFormProv.setLayout(pnlFormProvLayout);
        pnlFormProvLayout.setHorizontalGroup(
            pnlFormProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        pnlFormProvLayout.setVerticalGroup(
            pnlFormProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlOpcionesProveedorLayout = new javax.swing.GroupLayout(pnlOpcionesProveedor);
        pnlOpcionesProveedor.setLayout(pnlOpcionesProveedorLayout);
        pnlOpcionesProveedorLayout.setHorizontalGroup(
            pnlOpcionesProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFormProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformacionProveedor))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlOpcionesProveedorLayout.setVerticalGroup(
            pnlOpcionesProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesProveedorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRegistrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformacionProveedor)
                .addGap(18, 18, 18)
                .addComponent(pnlFormProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(pnlOpcionesProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 352, 610));

        pnlVentanaProv.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Proveedor", "Nombre", "Calle", "Colonia", "Activo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("TODOS LOS PROVEEDORES");

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar_Proveedor1.png"))); // NOI18N
        btnAgregar.setBorder(null);
        pnlBotones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 72, 60));

        lblAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(102, 102, 102));
        lblAgregar.setText("Agregar");
        pnlBotones.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        btnEditar.setBorder(null);
        pnlBotones.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 72, 60));

        lblEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(102, 102, 102));
        lblEditar.setText("Editar");
        pnlBotones.add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar_Proveedor.png"))); // NOI18N
        btnBuscar.setBorder(null);
        pnlBotones.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 72, 60));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(102, 102, 102));
        lblBuscar.setText("Buscar");
        pnlBotones.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eliminar_Proveedor.png"))); // NOI18N
        btnEliminar.setBorder(null);
        pnlBotones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 72, 60));

        lblEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(102, 102, 102));
        lblEliminar.setText("Eliminar");
        pnlBotones.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar-el-archivo.png"))); // NOI18N
        btnGuardar.setBorder(null);
        pnlBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 72, 60));

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(102, 102, 102));
        lblGuardar.setText("Guardar");
        pnlBotones.add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btnCancelar.setBorder(null);
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 72, 60));

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(102, 102, 102));
        lblCancelar.setText("Cancelar");
        pnlBotones.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        javax.swing.GroupLayout pnlVentanaProvLayout = new javax.swing.GroupLayout(pnlVentanaProv);
        pnlVentanaProv.setLayout(pnlVentanaProvLayout);
        pnlVentanaProvLayout.setHorizontalGroup(
            pnlVentanaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlVentanaProvLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(lblTitulo)
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVentanaProvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVentanaProvLayout.setVerticalGroup(
            pnlVentanaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanaProvLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlVentanaProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 830, 610));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblInformacionProveedor;
    private javax.swing.JLabel lblRegistrarProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFormProv;
    private javax.swing.JPanel pnlOpcionesProveedor;
    private javax.swing.JPanel pnlVentanaProv;
    // End of variables declaration//GEN-END:variables
}
