/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectospand.Interfaces.Empleados;

import java.awt.Color;

/**
 *
 * @author omarr
 */
public class RegistrarEmpleadosForm2 extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProveedoresForm2
     */
    public RegistrarEmpleadosForm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaContratoEmp = new javax.swing.JLabel();
        txtFechaContratoEmp = new javax.swing.JTextField();
        lblClaveEmp = new javax.swing.JLabel();
        txtClaveEmp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(230, 230, 250));

        lblFechaContratoEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaContratoEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblFechaContratoEmp.setText("Fecha de contrato*");

        txtFechaContratoEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaContratoEmp.setText("Ingresa la fecha del empleado");
        txtFechaContratoEmp.setEnabled(false);
        txtFechaContratoEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaContratoEmpFocusGained(evt);
            }
        });
        txtFechaContratoEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFechaContratoEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaContratoEmpMousePressed(evt);
            }
        });

        lblClaveEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClaveEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblClaveEmp.setText("Clave de ingreso*");

        txtClaveEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtClaveEmp.setText("Ingresa la clave del empleado");
        txtClaveEmp.setEnabled(false);
        txtClaveEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClaveEmpFocusGained(evt);
            }
        });
        txtClaveEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtClaveEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtClaveEmpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaContratoEmp)
                    .addComponent(txtFechaContratoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClaveEmp)
                    .addComponent(txtClaveEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaContratoEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaContratoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClaveEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClaveEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaContratoEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaContratoEmpFocusGained
        if (txtFechaContratoEmp.getText().equals("Ingresa la fecha del empleado")){
            txtFechaContratoEmp.setText("");
            txtFechaContratoEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaContratoEmpFocusGained

    private void txtFechaContratoEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaContratoEmpMousePressed
        if (txtFechaContratoEmp.getText().equals("Ingresa la fecha del empleado")){
            txtFechaContratoEmp.setText("");
            txtFechaContratoEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaContratoEmpMousePressed

    private void txtFechaContratoEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaContratoEmpMouseExited
        if (txtFechaContratoEmp.getText().isEmpty()){
            txtFechaContratoEmp.setText("Ingresa la fecha del empleado");
            txtFechaContratoEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtFechaContratoEmpMouseExited

    private void txtClaveEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveEmpFocusGained
        if (txtClaveEmp.getText().equals("Ingresa la clave del empleado")){
            txtClaveEmp.setText("");
            txtClaveEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtClaveEmpFocusGained

    private void txtClaveEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveEmpMousePressed
        if (txtClaveEmp.getText().equals("Ingresa la clave del empleado")){
            txtClaveEmp.setText("");
            txtClaveEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtClaveEmpMousePressed

    private void txtClaveEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveEmpMouseExited
        if (txtClaveEmp.getText().isEmpty()){
            txtClaveEmp.setText("Ingresa la clave del empleado");
            txtClaveEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtClaveEmpMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClaveEmp;
    private javax.swing.JLabel lblFechaContratoEmp;
    private javax.swing.JTextField txtClaveEmp;
    private javax.swing.JTextField txtFechaContratoEmp;
    // End of variables declaration//GEN-END:variables
}
