package com.proyectospand.Interfaces.Empleados;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import javax.swing.event.DocumentListener;

/**
 *
 * @author omarr
 */
public class RegistrarEmpleadoForm extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEmpleadoForm
     */
    public RegistrarEmpleadoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreEmp = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        lblApellidosEmp = new javax.swing.JLabel();
        txtApellidosEmp = new javax.swing.JTextField();
        lblCalleEmp = new javax.swing.JLabel();
        txtCalleEmp = new javax.swing.JTextField();
        lblNumeroEmp = new javax.swing.JLabel();
        txtNumeroEmp = new javax.swing.JTextField();
        lblColoniaEmp = new javax.swing.JLabel();
        txtColoniaEmp = new javax.swing.JTextField();
        lblNssEmp = new javax.swing.JLabel();
        txtNssEmp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(230, 230, 250));
        setPreferredSize(new java.awt.Dimension(338, 452));

        lblNombreEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblNombreEmp.setText("Nombre del Empleado*");

        txtNombreEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreEmp.setText("Ingresa el nombre del empleado");
        txtNombreEmp.setEnabled(false);
        txtNombreEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreEmpFocusGained(evt);
            }
        });
        txtNombreEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreEmpMousePressed(evt);
            }
        });

        lblApellidosEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidosEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblApellidosEmp.setText("Apellidos del Empleado*");

        txtApellidosEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidosEmp.setText("Ingresa los apellidos del empleado");
        txtApellidosEmp.setEnabled(false);
        txtApellidosEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidosEmpFocusGained(evt);
            }
        });
        txtApellidosEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtApellidosEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosEmpMousePressed(evt);
            }
        });

        lblCalleEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCalleEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblCalleEmp.setText("Calle del Empleado*");

        txtCalleEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtCalleEmp.setText("Ingresa la calle del empleado");
        txtCalleEmp.setEnabled(false);
        txtCalleEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCalleEmpFocusGained(evt);
            }
        });
        txtCalleEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCalleEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCalleEmpMousePressed(evt);
            }
        });

        lblNumeroEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroEmp.setText("Numero de casa del Empleado*");

        txtNumeroEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtNumeroEmp.setText("Ingresa el numero del empleado");
        txtNumeroEmp.setEnabled(false);
        txtNumeroEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroEmpFocusGained(evt);
            }
        });
        txtNumeroEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNumeroEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroEmpMousePressed(evt);
            }
        });

        lblColoniaEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblColoniaEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblColoniaEmp.setText("Colonia del Empleado*");

        txtColoniaEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtColoniaEmp.setText("Ingresa la colonia del empleado");
        txtColoniaEmp.setEnabled(false);
        txtColoniaEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColoniaEmpFocusGained(evt);
            }
        });
        txtColoniaEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtColoniaEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtColoniaEmpMousePressed(evt);
            }
        });

        lblNssEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNssEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblNssEmp.setText("NSS del Empleado*");

        txtNssEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtNssEmp.setText("Ingresa el NSS del empleado");
        txtNssEmp.setEnabled(false);
        txtNssEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNssEmpFocusGained(evt);
            }
        });
        txtNssEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNssEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNssEmpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmp)
                    .addComponent(txtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidosEmp)
                    .addComponent(txtApellidosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalleEmp)
                    .addComponent(txtCalleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroEmp)
                    .addComponent(txtNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColoniaEmp)
                    .addComponent(txtColoniaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNssEmp)
                    .addComponent(txtNssEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblApellidosEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCalleEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCalleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblColoniaEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtColoniaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNssEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNssEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEmpMousePressed
        if(txtNombreEmp.getText().equals("Ingresa el nombre del empleado")){
            txtNombreEmp.setText("");
            txtNombreEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreEmpMousePressed

    private void txtNombreEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreEmpFocusGained
        if(txtNombreEmp.getText().equals("Ingresa el nombre del empleado")){
            txtNombreEmp.setText("");
            txtNombreEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreEmpFocusGained

    private void txtNombreEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEmpMouseExited
        if (txtNombreEmp.getText().isEmpty()){
            txtNombreEmp.setText("Ingresa el nombre del empleado");
            txtNombreEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtNombreEmpMouseExited

    private void txtApellidosEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosEmpMousePressed
        if(txtApellidosEmp.getText().equals("Ingresa los apellidos del empleado")){
            txtApellidosEmp.setText("");
            txtApellidosEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtApellidosEmpMousePressed

    private void txtApellidosEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosEmpMouseExited
        if (txtApellidosEmp.getText().isEmpty()){
            txtApellidosEmp.setText("Ingresa los apellidos del empleado");
            txtApellidosEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtApellidosEmpMouseExited

    private void txtCalleEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleEmpMousePressed
        if(txtCalleEmp.getText().equals("Ingresa la calle del empleado")){
            txtCalleEmp.setText("");
            txtCalleEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCalleEmpMousePressed

    private void txtCalleEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleEmpMouseExited
        if(txtCalleEmp.getText().isEmpty()){
            txtCalleEmp.setText("Ingresa la calle del Empleado");
            txtCalleEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtCalleEmpMouseExited

    private void txtApellidosEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosEmpFocusGained
        if(txtApellidosEmp.getText().equals("Ingresa los apellidos del empleado")){
            txtApellidosEmp.setText("");
            txtApellidosEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtApellidosEmpFocusGained

    private void txtCalleEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleEmpFocusGained
        if(txtCalleEmp.getText().equals("Ingresa la calle del empleado")){
            txtCalleEmp.setText("");
            txtCalleEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCalleEmpFocusGained

    private void txtNumeroEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroEmpFocusGained
        if (txtNumeroEmp.getText().equals("Ingresa el numero del empleado")){
            txtNumeroEmp.setText("");
            txtNumeroEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNumeroEmpFocusGained

    private void txtNumeroEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroEmpMousePressed
        if (txtNumeroEmp.getText().equals("Ingresa el numero del empleado")){
            txtNumeroEmp.setText("");
            txtNumeroEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNumeroEmpMousePressed

    private void txtNumeroEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroEmpMouseExited
        if (txtNumeroEmp.getText().isEmpty()){
            txtNumeroEmp.setText("Ingresa el numero del empleado");
            txtNumeroEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtNumeroEmpMouseExited

    private void txtColoniaEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColoniaEmpFocusGained
        if (txtColoniaEmp.getText().equals("Ingresa la colonia del empleado")){
            txtColoniaEmp.setText("");
            txtColoniaEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtColoniaEmpFocusGained

    private void txtColoniaEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColoniaEmpMousePressed
        if (txtColoniaEmp.getText().equals("Ingresa la colonia del empleado")){
            txtColoniaEmp.setText("");
            txtColoniaEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtColoniaEmpMousePressed

    private void txtColoniaEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColoniaEmpMouseExited
        if (txtColoniaEmp.getText().isEmpty()){
            txtColoniaEmp.setText("Ingresa la colonia del empleado");
            txtColoniaEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtColoniaEmpMouseExited

    private void txtNssEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNssEmpFocusGained
        if (txtNssEmp.getText().equals("Ingresa el NSS del empleado")){
            txtNssEmp.setText("");
            txtNssEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNssEmpFocusGained

    private void txtNssEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNssEmpMousePressed
        if (txtNssEmp.getText().equals("Ingresa el NSS del empleado")){
            txtNssEmp.setText("");
            txtNssEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNssEmpMousePressed

    private void txtNssEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNssEmpMouseExited
       if (txtNssEmp.getText().isEmpty()){
            txtNssEmp.setText("Ingresa el NSS del empleado");
            txtNssEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtNssEmpMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblApellidosEmp;
    private javax.swing.JLabel lblCalleEmp;
    private javax.swing.JLabel lblColoniaEmp;
    private javax.swing.JLabel lblNombreEmp;
    private javax.swing.JLabel lblNssEmp;
    private javax.swing.JLabel lblNumeroEmp;
    private javax.swing.JTextField txtApellidosEmp;
    private javax.swing.JTextField txtCalleEmp;
    private javax.swing.JTextField txtColoniaEmp;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextField txtNssEmp;
    private javax.swing.JTextField txtNumeroEmp;
    // End of variables declaration//GEN-END:variables
}
