/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyectospand.Interfaces.Empleados;

import java.awt.Color;

/**
 *
 * @author omarr
 */
public class RegistrarEmpleadosForm2 extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProveedoresForm2
     */
    public RegistrarEmpleadosForm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaContratoEmp = new javax.swing.JLabel();
        txtFechaContratoEmp = new javax.swing.JTextField();
        lblTelefonoEmp = new javax.swing.JLabel();
        txtTelefonoEmp = new javax.swing.JTextField();
        lblClaveEmp = new javax.swing.JLabel();
        txtPassClaveEmp = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(230, 230, 250));

        lblFechaContratoEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaContratoEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblFechaContratoEmp.setText("Fecha de contrato*");

        txtFechaContratoEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaContratoEmp.setText("Ingresa la fecha del empleado");
        txtFechaContratoEmp.setEnabled(false);
        txtFechaContratoEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaContratoEmpFocusGained(evt);
            }
        });
        txtFechaContratoEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFechaContratoEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaContratoEmpMousePressed(evt);
            }
        });

        lblTelefonoEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefonoEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefonoEmp.setText("Teléfono*");

        txtTelefonoEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoEmp.setText("Ingresa el teléfono del empleado");
        txtTelefonoEmp.setEnabled(false);
        txtTelefonoEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoEmpFocusGained(evt);
            }
        });
        txtTelefonoEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelefonoEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoEmpMousePressed(evt);
            }
        });

        lblClaveEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClaveEmp.setForeground(new java.awt.Color(102, 102, 102));
        lblClaveEmp.setText("Clave de ingreso*");

        txtPassClaveEmp.setText("***************");
        txtPassClaveEmp.setEnabled(false);
        txtPassClaveEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassClaveEmpFocusGained(evt);
            }
        });
        txtPassClaveEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPassClaveEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassClaveEmpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPassClaveEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(lblFechaContratoEmp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaContratoEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(lblClaveEmp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonoEmp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaContratoEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaContratoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelefonoEmp)
                .addGap(4, 4, 4)
                .addComponent(txtTelefonoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClaveEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassClaveEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaContratoEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaContratoEmpFocusGained
        if (txtFechaContratoEmp.getText().equals("Ingresa la fecha del empleado")){
            txtFechaContratoEmp.setText("");
            txtFechaContratoEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaContratoEmpFocusGained

    private void txtFechaContratoEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaContratoEmpMousePressed
        if (txtFechaContratoEmp.getText().equals("Ingresa la fecha del empleado")){
            txtFechaContratoEmp.setText("");
            txtFechaContratoEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaContratoEmpMousePressed

    private void txtFechaContratoEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaContratoEmpMouseExited
        if (txtFechaContratoEmp.getText().isEmpty()){
            txtFechaContratoEmp.setText("Ingresa la fecha del empleado");
            txtFechaContratoEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtFechaContratoEmpMouseExited

    private void txtTelefonoEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoEmpFocusGained
        if (txtTelefonoEmp.getText().equals("Ingresa el teléfono del empleado")){
            txtTelefonoEmp.setText("");
            txtTelefonoEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoEmpFocusGained

    private void txtTelefonoEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoEmpMouseExited
        if (txtTelefonoEmp.getText().isEmpty()){
            txtTelefonoEmp.setText("Ingresa el teléfono del empleado");
            txtTelefonoEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtTelefonoEmpMouseExited

    private void txtTelefonoEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoEmpMousePressed
        if (txtTelefonoEmp.getText().equals("Ingresa el teléfono del empleado")){
            txtTelefonoEmp.setText("");
            txtTelefonoEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoEmpMousePressed

    private void txtPassClaveEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassClaveEmpFocusGained
        if (String.valueOf(txtPassClaveEmp.getPassword()).equals("***************")){
            txtPassClaveEmp.setText("");
            txtPassClaveEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPassClaveEmpFocusGained

    private void txtPassClaveEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassClaveEmpMousePressed
        if (String.valueOf(txtPassClaveEmp.getPassword()).equals("***************")){
            txtPassClaveEmp.setText("");
            txtPassClaveEmp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPassClaveEmpMousePressed

    private void txtPassClaveEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassClaveEmpMouseExited
        if (String.valueOf(txtPassClaveEmp.getPassword()).isEmpty()){
            txtPassClaveEmp.setText("***************");
            txtPassClaveEmp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtPassClaveEmpMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClaveEmp;
    private javax.swing.JLabel lblFechaContratoEmp;
    private javax.swing.JLabel lblTelefonoEmp;
    private javax.swing.JTextField txtFechaContratoEmp;
    private javax.swing.JPasswordField txtPassClaveEmp;
    private javax.swing.JTextField txtTelefonoEmp;
    // End of variables declaration//GEN-END:variables
}
